### ISSUE TITLE
Reload when changes

### ISSUE THREAD

**Issue by jsga** [ericcgu/Flask-Dash-Plotly#1]
Hello!
First of all, thanks for sharing, it was quite helpful :)
I have two issues/questions:

1. Is it possible to see changes without reloading the whole image, when something in _app.py_ changes? (for example, a new line is added or a typo is corrected)
2. Let's say you make a mistake in app.py and it crashes. How can you see the error messages?

**Comment by ericcgu** [comment]
For #1:https://nickjanetakis.com/blog/docker-tip-12-a-much-better-development-experience-with-volumes

**Comment by ericcgu** [comment]
For number two I am not quite following.

**Comment by jsga** [comment]
For 1, if I understood correctly,  docker_compose.yml should look like this: (note the volumes option)

```
version: '3'

services:

  dash:
    container_name: dash
    restart: always
    build: ./dash
    volumes:
      - '.:/home/project/dash'
    ports:
      - "8000:8000"
    command: gunicorn -w 1 -b :8000 app:server


  nginx:
    container_name: nginx
    restart: always
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - dash
```

Nothing appears in [http://localhost:8000/](http://localhost:8000/), neither any error in the console. I must be missing something :/

Let's forget about 2 for now :)
